src/web/EnterpriseApp.WebApp.MVC/Models/OrderViewModel.cs
using System;
using System.Collections.Generic;

namespace EnterpriseApp.WebApp.MVC.Models
{
    public class OrderViewModel
    {
        #region Pedido
        public int Code { get; set; }
        // Autorizado = 1,
        // Pago = 2,
        // Recusado = 3,
        // Entregue = 4,
        // Cancelado = 5
        public int Status { get; set; }
        public DateTime Date { get; set; }
        public decimal TotalPrice { get; set; }
        public decimal Discount { get; set; }
        public bool HasUsedVoucher { get; set; }
        public List<ItemOrderViewModel> OrderItems { get; set; } = new List<ItemOrderViewModel>();
        #endregion

        #region Order Item
        public class ItemOrderViewModel
        {
            public Guid ProductId { get; set; }
            public string Name { get; set; }
            public int Quantity { get; set; }
            public decimal Price { get; set; }
            public string Image { get; set; }
        }
        #endregion

        #region Address
        public AddressViewModel Address { get; set; }
        #endregion
    }
}

src/web/EnterpriseApp.WebApp.MVC/Controllers/CustomerController.cs
using EnterpriseApp.WebApp.MVC.Models;
using EnterpriseApp.WebApp.MVC.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace EnterpriseApp.WebApp.MVC.Controllers
{
    [Authorize]
    public class CustomerController : MainController
    {
        private readonly ICustomersService _customersService;

        public CustomerController(ICustomersService customersService)
        {
            _customersService = customersService;
        }
        
        [HttpPost("addresses")]
        public async Task<IActionResult> NewAddress(AddressViewModel address)
        {
            var response = await _customersService.AddAddress(address);

            if (ResponsePossuiErros(response))
            {
                TempData["Erros"] = ModelState.Values.SelectMany(v => v.Errors.Select(e => e.ErrorMessage)).ToList();
            }

            return RedirectToAction("EnderecoEntrega", "Pedido");
        }
    }
}

src/web/EnterpriseApp.WebApp.MVC/Controllers/OrdersController.cs
using EnterpriseApp.WebApp.MVC.Models;
using EnterpriseApp.WebApp.MVC.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace EnterpriseApp.WebApp.MVC.Controllers
{
    public class OrdersController : MainController
    {
        private readonly ICustomersService _customersService;
        private readonly IPurchaseBffService _purchaseBffService;

        public OrdersController(
            ICustomersService customersService,
            IPurchaseBffService purchaseBffService)
        {
            _customersService = customersService;
            _purchaseBffService = purchaseBffService;
        }

        [HttpGet]
        [Route("delivery-address")]
        public async Task<IActionResult> DeliveryAddress()
        {
            var cart = await _purchaseBffService.GetShoppingCart();

            if (cart.Items.Count == 0)
                return RedirectToAction("Index", "Cart");

            var address = await _customersService.GetAddress();

            var order = _purchaseBffService.MapToTransactionOrder(cart, address);

            return View(order);
        }

        [HttpGet]
        [Route("payment")]
        public async Task<IActionResult> Payment()
        {
            var cart = await _purchaseBffService.GetShoppingCart();

            if (cart.Items.Count == 0)
                return RedirectToAction("Index", "Cart");

            var order = _purchaseBffService.MapToTransactionOrder(cart, null);

            return View(order);
        }

        [HttpPost]
        [Route("finish-order")]
        public async Task<IActionResult> FinishOrder(OrderTransactionViewModel transactionOrder)
        {
            if (!ModelState.IsValid) 
                return View("Payment", _purchaseBffService.MapToTransactionOrder(await _purchaseBffService.GetShoppingCart(), null));

            var response = await _purchaseBffService.FinishOrder(transactionOrder);

            if (ResponsePossuiErros(response))
            {
                var cart = await _purchaseBffService.GetShoppingCart();

                if (cart.Items.Count == 0) 
                    return RedirectToAction("Index", "Cart");

                var orderMap = _purchaseBffService.MapToTransactionOrder(cart, null);

                return View("Payment", orderMap);
            }

            return RedirectToAction("OrderFinished");
        }

        [HttpGet]
        [Route("order-finished")]
        public async Task<IActionResult> OrderFinished()
            => View("OrderConfirmation", await _purchaseBffService.GetLastOrder());

        [HttpGet("my-orders")]
        public async Task<IActionResult> MyOrders()
            => View(await _purchaseBffService.GetOrderListByCustomerId());
    }
}

src/web/EnterpriseApp.WebApp.MVC/Views/Orders/DeliveryAddress.cshtml
@using EnterpriseApp.WebApp.MVC.Extensions
@model EnterpriseApp.WebApp.MVC.Models.OrderTransactionViewModel

@{
    ViewData["Title"] = "Confirm your order";
}

<section class="padding-y">
    <div class="container">

        <vc:Summary></vc:Summary>

        @{
            if (Model.Items.Any())
            {
                <div class="card">
                    <div class="tracking-wrap">
                        <div class="step active">
                            <span class="icon">
                                <i class="fa fa-location-arrow"></i>
                            </span>
                            <span class="text"> Address</span>
                        </div>
                        <div class="step">
                            <span class="icon">
                                <i class="fa fa-credit-card"></i>
                            </span>
                            <span class="text"> Payment </span>
                        </div>
                        <div class="step">
                            <span class="icon">
                                <i class="fa fa-check-square"></i>
                            </span>
                            <span class="text"> Confirmation</span>
                        </div>
                    </div>
                    <article class="card-body">
                        <header class="mb-4">
                            <h4 class="card-title">Seu pedido</h4>
                        </header>
                        <div class="row">
                            @{
                                foreach (var item in Model.Items)
                                {
                                    <div class="col-md-6">
                                        <figure class="itemside  mb-3">
                                            <div class="aside">
                                                <img src="~/images/produtos/@item.Image" alt="@item.Name" class="border img-xs">
                                            </div>
                                            <figcaption class="info">
                                                <p>
                                                    <b>@item.Name</b>
                                                </p>
                                                <span>@this.UnitiesPerProductTotalPrice(item.Quantity, item.Price) </span>
                                            </figcaption>
                                        </figure>
                                    </div>
                                }
                            }

                        </div>
                    </article>

                    <partial name="_FinancialSummary" model="Model" />

                    <div class="card-body border-top">
                        <partial name="_Address" model="Model" />
                    </div>
                    <div class="card-body border-top">
                        @{
                            if (Model.Address != null)
                            {
                                <div class="text-left">
                                    <a asp-controller="Orders" asp-action="Payment" class="btn btn-primary float-md-right"> Payment <i class="fa fa-chevron-right"></i> </a>
                                </div>
                            }
                        }

                        <a asp-controller="Cart" asp-action="Index" class="btn btn-light"> <i class="fa fa-chevron-left"></i> Back to shopping cart</a>
                    </div>
                </div>
            }
        }
    </div>
</section>

<partial name="_NewAddress" />

@section Scripts {

    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        $(document).ready(function () {
            BuscaCep();
        });
    </script>

}

src/web/EnterpriseApp.WebApp.MVC/Views/Orders/MyOrders.cshtml
@using EnterpriseApp.WebApp.MVC.Extensions
@model IEnumerable<EnterpriseApp.WebApp.MVC.Models.OrderViewModel>

@{
    ViewData["Title"] = "My Orders";
}

<section class="padding-y">
    <div class="container">

        @{
            foreach (var pedido in Model.OrderBy(p => p.Date))
            {
                <div class="col-md-12" style="padding-bottom: 35px">
                    <article class="card">
                        <header class="card-header">
                            <b class="d-inline-block mr-3">Pedido ID: #@pedido.Code @Html.Raw(this.ShowStatus(pedido.Status))</b>
                            <span>@pedido.Date.ToLongDateString()</span>
                        </header>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-4">
                                    <h6 class="text-muted">Pagamento</h6>
                                    <span class="text-success">
                                        <i class="fas fa-credit-card"></i>
                                        Transação em cartão de crédito
                                    </span>

                                    <p>
                                        <span class="b">Total:  @this.FormatCurrency(pedido.TotalPrice)</span>
                                    </p>

                                </div>
                                <div class="col-md-8">
                                    <h6 class="text-muted">Endereço de entrega</h6>
                                    <p>
                                        @pedido.Address.ToString()
                                    </p>
                                </div>
                            </div>
                            <hr>
                            <ul class="row">
                                @{
                                    foreach (var item in pedido.OrderItems)
                                    {
                                        <li class="col-md-4">
                                            <figure class="itemside  mb-3">
                                                <div class="aside">
                                                    <img src="~/images/produtos/@item.Image" alt="@item.Name" class="border img-xs">
                                                </div>
                                                <figcaption class="info">
                                                    <p>
                                                        <b>@item.Name</b>
                                                    </p>
                                                    <span>@this.UnitiesPerProductTotalPrice(item.Quantity, item.Price) </span>
                                                </figcaption>
                                            </figure>
                                        </li>

                                    }
                                }
                            </ul>
                        </div>
                    </article>
                </div>
            }
        }
    </div>
</section>

src/web/EnterpriseApp.WebApp.MVC/Views/Orders/OrderConfirmation.cshtml
@using EnterpriseApp.WebApp.MVC.Extensions
@model EnterpriseApp.WebApp.MVC.Models.OrderViewModel

@{
    ViewData["Title"] = "Order Confirmed!";
}

<section class="padding-y">
    <div class="container">

        <vc:Summary></vc:Summary>

        @{
            if (Model.OrderItems.Any())
            {
                <div class="card">
                    <div class="tracking-wrap">
                        <div class="step active">
                            <span class="icon">
                                <i class="fa fa-location-arrow"></i>
                            </span>
                            <span class="text"> Address</span>
                        </div>
                        <div class="step active">
                            <span class="icon">
                                <i class="fa fa-credit-card"></i>
                            </span>
                            <span class="text"> Payment </span>
                        </div>
                        <div class="step active">
                            <span class="icon">
                                <i class="fa fa-check-square"></i>
                            </span>
                            <span class="text"> Confirmation</span>
                        </div>
                    </div>
                    <article class="card-body">
                        <header class="mb-4">
                            <h4 class="card-title">Pedido concluído com sucesso!</h4>
                        </header>
                        <div class="row">
                            @{
                                foreach (var item in Model.OrderItems)
                                {
                                    <div class="col-md-6">
                                        <figure class="itemside  mb-3">
                                            <div class="aside">
                                                <img src="~/images/produtos/@item.Image" alt="@item.Name" class="border img-xs">
                                            </div>
                                            <figcaption class="info">
                                                <p>
                                                    <b>@item.Name</b>
                                                </p>
                                                <span>@this.UnitiesPerProductTotalPrice(item.Quantity, item.Price) </span>
                                            </figcaption>
                                        </figure>
                                    </div>
                                }
                            }

                        </div>
                    </article>

                    <header class="card-header">
                        <h3 class="d-inline-block mr-3">Number Code: #@Model.Code</h3>
                    </header>
                    <article class="card-body border-top">

                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-8">
                                    <h6 class="text-muted">Delivery Address: </h6>
                                    <p>
                                        @Model.Address.ToString()
                                    </p>
                                </div>
                                <div class="col-md-4">
                                    <h6 class="text-muted">Payment</h6>
                                    <span class="text-success">
                                        <i class="fas fa-credit-card"></i>
                                        Credit Card Transaction
                                    </span>
                                    <p>
                                        <span class="b">Total:  @this.FormatCurrency(Model.TotalPrice)</span>
                                    </p>
                                </div>
                            </div>

                        </div>
                    </article>

                    <div class="card-body border-top">
                        <div class="text-left">
                            <a asp-controller="Orders" asp-action="MyOrders" class="btn btn-primary float-md-right"> My Orders <i class="fa fa-chevron-right"></i> </a>
                        </div>
                    </div>

                </div>
            }
        }
    </div>
</section>

@section Scripts {

    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

}

src/web/EnterpriseApp.WebApp.MVC/Views/Orders/Payment.cshtml
@using EnterpriseApp.WebApp.MVC.Extensions
@model EnterpriseApp.WebApp.MVC.Models.OrderTransactionViewModel

@{
    ViewData["Title"] = "Confirm your order";
}

<section class="padding-y">
    <div class="container">

        <vc:Summary></vc:Summary>

        @{
            if (Model.Items.Any())
            {
                <div class="card">
                    <div class="tracking-wrap">
                        <div class="step active">
                            <span class="icon">
                                <i class="fa fa-location-arrow"></i>
                            </span>
                            <span class="text"> Address</span>
                        </div>
                        <div class="step active">
                            <span class="icon">
                                <i class="fa fa-credit-card"></i>
                            </span>
                            <span class="text"> Payment </span>
                        </div>
                        <div class="step">
                            <span class="icon">
                                <i class="fa fa-check-square"></i>
                            </span>
                            <span class="text"> Confirmation</span>
                        </div>
                    </div>
                    <article class="card-body">
                        <header class="mb-4">
                            <h4 class="card-title">Your Order</h4>
                        </header>
                        <div class="row">
                            @{
                                foreach (var item in Model.Items)
                                {
                                    <div class="col-md-6">
                                        <figure class="itemside  mb-3">
                                            <div class="aside">
                                                <img src="~/images/produtos/@item.Image" alt="@item.Name" class="border img-xs">
                                            </div>
                                            <figcaption class="info">
                                                <p>
                                                    <b>@item.Name</b>
                                                </p>
                                                <span>@this.UnitiesPerProductTotalPrice(item.Quantity, item.Price) </span>
                                            </figcaption>
                                        </figure>
                                    </div>
                                }
                            }

                        </div>
                    </article>

                    <partial name="_FinancialSummary" model="Model" />

                    <form asp-action="FinishOrder" asp-controller="Orders">
                        <article class="card-body border-top">

                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-4 col-sm-12">
                                        <div class="form-group">
                                            <label asp-for="CardName"></label>
                                            <input asp-for="CardName" class="form-control" />
                                            <span asp-validation-for="CardName" class="text-danger"></span>
                                        </div>
                                    </div>
                                    <div class="col-md-4 col-sm-12">
                                        <div class="form-group">
                                            <label asp-for="CardNumber"></label>
                                            <div class="input-group">
                                                <input asp-for="CardNumber" class="form-control" />
                                                <div class="input-group-append">
                                                    <span class="input-group-text">
                                                        <i class="fab fa-cc-visa"></i> &nbsp; <i class="fab fa-cc-amex"></i> &nbsp;
                                                        <i class="fab fa-cc-mastercard"></i>
                                                    </span>
                                                </div>
                                                <span asp-validation-for="CardNumber" class="text-danger"></span>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-4 col-sm-12">
                                        <div>
                                            <label asp-for="CardExpirationDate"></label>
                                            <div class="form-inline">
                                                <input style="width: 190px" asp-for="CardExpirationDate" class="form-control" />
                                                <span asp-validation-for="CardExpirationDate" class="text-danger"></span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4 col-sm-12">
                                        <div>
                                            <spam data-toggle="tooltip" title="" data-original-title="The 3 digits behind your credit card.">
                                                <label asp-for="CardCvv"></label> <i class="fa fa-question-circle"></i>
                                            </spam>

                                            <div>
                                                <input style="width: 160px" asp-for="CardCvv" class="form-control" />
                                                <span asp-validation-for="CardCvv" class="text-danger"></span>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </article>

                        <div class="card-body border-top">
                            <div class="text-left">
                                <button type="submit" class="btn btn-primary float-md-right"> Finish Order <i class="fa fa-chevron-right"></i> </button>
                            </div>

                            <a asp-controller="Orders" asp-action="DeliveryAddress" class="btn btn-light"> <i class="fa fa-chevron-left"></i> Back to Address </a>
                        </div>
                    </form>
                </div>
            }
        }
    </div>
</section>

@section Scripts {

    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}

src/web/EnterpriseApp.WebApp.MVC/Views/Orders/_Address.cshtml
@model EnterpriseApp.WebApp.MVC.Models.OrderTransactionViewModel

<h4 class="card-title">Address</h4>
@{
    if (Model.Address is null)
    {
        <div class="text-left">
            <a href="javascript:void(0)" class="btn btn-primary float-md-left" data-toggle="modal" data-target="#enderecoModal"> <i class="fa fa-location-arrow"></i> Add Address</a>
        </div>
    }
    else
    {
        <div class="row">
            <div class="col-9 text-left">
                @Model.Address.ToString()
            </div>
            <div class="col-3 text-right">
                <a href="javascript:void(0)" class="btn btn-primary float-md-right"> <i class="fa fa-location-arrow"></i> Change Address</a>
            </div>
        </div>
    }
}

src/web/EnterpriseApp.WebApp.MVC/Views/Orders/_FinancialSummary.cshtml
@using EnterpriseApp.WebApp.MVC.Extensions
@model EnterpriseApp.WebApp.MVC.Models.OrderTransactionViewModel

<article class="card-body border-top">
    <dl class="row">
        @{
            if (Model.HasUsedVoucher)
            {
                <dt class="col-sm-10">Subtotal: <span class="float-right text-muted">@Model.Items.Sum(i => i.Quantity) items</span></dt>
                <dd class="col-sm-2 text-right">
                    <strong>@this.FormatCurrency(Model.TotalPrice + Model.Discount)</strong>
                </dd>

                <dt class="col-sm-10">Discount: <span class="float-right text-muted">@Model.VoucherCode</span></dt>
                <dd class="col-sm-2 text-danger text-right">
                    <strong>@this.FormatCurrency(Model.Discount)</strong>
                </dd>
            }
        }
        <dt class="col-sm-10">Total:</dt>
        <dd class="col-sm-2 text-right">
            <strong class="h5 text-dark">@this.FormatCurrency(Model.TotalPrice)</strong>
        </dd>
    </dl>
</article>

src/web/EnterpriseApp.WebApp.MVC/Views/Orders/_NewAddress.cshtml
@model EnterpriseApp.WebApp.MVC.Models.OrderTransactionViewModel
@{
    ViewData["Title"] = "New Address";
}

<div class="modal fade" id="enderecoModal" tabindex="-1" role="dialog" aria-labelledby="enderecoModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div id="myModalContent">

                <div class="modal-header">
                    <h4 class="modal-title">@ViewData["Title"]</h4>
                    <button type="button" class="close" data-dismiss="modal">
                        <span aria-hidden="true">×</span><span class="sr-only">Close</span>
                    </button>
                </div>

                <form asp-action="NewAddress" asp-controller="Customer">
                    <div class="modal-body">

                        <div class="form-group">
                            <label asp-for="Address.Cep"></label>
                            <input asp-for="Address.Cep" class="form-control" />
                            <span asp-validation-for="Address.Cep" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Address.Street"></label>
                            <input asp-for="Address.Street" class="form-control" />
                            <span asp-validation-for="Address.Street" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Address.Number"></label>
                            <input asp-for="Address.Number" class="form-control" />
                            <span asp-validation-for="Address.Number" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Address.Complement"></label>
                            <input asp-for="Address.Complement" class="form-control" />
                            <span asp-validation-for="Address.Complement" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Address.Neighbourhood"></label>
                            <input asp-for="Address.Neighbourhood" class="form-control" />
                            <span asp-validation-for="Address.Neighbourhood" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Address.City"></label>
                            <input asp-for="Address.City" class="form-control" />
                            <span asp-validation-for="Address.City" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Address.State"></label>
                            <input asp-for="Address.State" class="form-control" />
                            <span asp-validation-for="Address.State" class="text-danger"></span>
                        </div>

                        <div class="modal-footer">
                            <div>
                                <input type="submit" value="Register Address" class="btn btn-success" />
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    BuscaCep();
</script>