src/web/EnterpriseApp.WebApp.MVC/Controllers/CartController.cs
using EnterpriseApp.WebApp.MVC.Models;
using EnterpriseApp.WebApp.MVC.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace EnterpriseApp.WebApp.MVC.Controllers
{
    [Authorize]
    [Route("shopping-cart")]
    public class CartController : MainController
    {
        private readonly IPurchaseBffService _purchaseBffService;

        public CartController(IPurchaseBffService purchaseBffService)
        {
            _purchaseBffService = purchaseBffService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _purchaseBffService.GetShoppingCart());
        }

        [HttpPost]
        [Route("add-item")]
        public async Task<IActionResult> AddItemAtCart(ItemShoppingCartViewModel itemProduct)
        {
            var resposta = await _purchaseBffService.AddShoppingCartItem(itemProduct);

            if (ResponsePossuiErros(resposta)) return View("Index", await _purchaseBffService.GetShoppingCart());

            return RedirectToAction("Index");
        }

        [HttpPost]
        [Route("update-item")]
        public async Task<IActionResult> UpdateCartItem(Guid produtoId, int quantidade)
        {
            var item = new ItemShoppingCartViewModel { ProductId = produtoId, Quantity = quantidade };
            var resposta = await _purchaseBffService.UpdateShoppingCartItem(produtoId, item);

            if (ResponsePossuiErros(resposta)) return View("Index", await _purchaseBffService.GetShoppingCart());

            return RedirectToAction("Index");
        }

        [HttpPost]
        [Route("remove-item")]
        public async Task<IActionResult> RemoveItemFromCart(Guid produtoId)
        {
            var resposta = await _purchaseBffService.RemoveShoppingCartItem(produtoId);

            if (ResponsePossuiErros(resposta)) return View("Index", await _purchaseBffService.GetShoppingCart());

            return RedirectToAction("Index");
        }

        [HttpPost]
        [Route("apply-voucher")]
        public async Task<IActionResult> ApplyVoucher(string voucherCodigo)
        {
            var resposta = await _purchaseBffService.ApplyVoucherShoppingCart(voucherCodigo);

            if (ResponsePossuiErros(resposta)) return View("Index", await _purchaseBffService.GetShoppingCart());

            return RedirectToAction("Index");
        }
    }
}

src/web/EnterpriseApp.WebApp.MVC/Controllers/CatalogController.cs
using EnterpriseApp.WebApp.MVC.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace EnterpriseApp.WebApp.MVC.Controllers
{
    [ApiController]
    public class CatalogController : Controller
    {
        private readonly ICatalogService _catalogService;

        public CatalogController(ICatalogService catalogService)
        {
            _catalogService = catalogService;
        }

        [HttpGet]
        [Route("")]
        [Route("catalog")]
        public async Task<IActionResult> Index(
            [FromQuery] int pageSize = 8,
            [FromQuery] int pageIndex = 1,
            [FromQuery] string query = null)
        {
            var products = await _catalogService.GetAllProducts(pageSize, pageIndex, query);

            ViewBag.Pesquisa = query;
            products.ReferenceAction = "Index";

            return View(products);
        }

        [HttpGet]
        [Route("product-details/{id}")]
        public async Task<IActionResult> ProductDetails(Guid id)
            => View(await _catalogService.GetProduct(id));
    }
}

src/web/EnterpriseApp.WebApp.MVC/Extensions/PaginacaoViewComponent.cs
using EnterpriseApp.WebApp.MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace EnterpriseApp.WebApp.MVC.Extensions
{
    public class PaginacaoViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(IPagedViewModel modeloPaginado)
            => View(modeloPaginado);
    }
}

src/web/EnterpriseApp.WebApp.MVC/Views/Catalog/Index.cshtml
@using EnterpriseApp.WebApp.MVC.Extensions
@model PagedViewModel<EnterpriseApp.WebApp.MVC.Models.ProductViewModel>

@{
    ViewData["Title"] = "All the products";
}

<section>
    <div>
        <div style="background-image: url(images/banners/Template.jpg); height: 100%; background-position: center; background-repeat: no-repeat; background-size: cover">
            <div style="text-align: center;">
                <img src="~/images/banners/nerdstore.png" />
            </div>
        </div>
        <div class="container" style=" padding-top: 20px">
            <div class="row">
                @{
                    foreach (var product in Model.List.OrderBy(p => p.Name))
                    {
                        <div class="col-md-3">
                            <div href="#" class="card card-product-grid">
                                <a asp-controller="Catalog" asp-action="ProductDetails" asp-route-id="@product.Id" class="img-wrap">
                                    <img src="~/images/produtos/@product.Image" alt="@product.Name">
                                </a>
                                <figcaption class="info-wrap">
                                    <a asp-controller="Catalog" asp-action="ProductDetails" asp-route-id="@product.Id" class="title">
                                        <b> @product.Name</b>
                                    </a>

                                    <small class="card-text">
                                        @this.StockMessage(product.StockQuantity)<br /><br />
                                        @product.Description
                                    </small>
                                </figcaption>
                                <div class="card-footer price mt-1">
                                    <h3>@this.FormatCurrency(@product.Price)</h3>
                                </div>
                            </div>
                        </div>
                    }
                }
            </div>
            
            <vc:paginacao modelo-paginado="@Model"></vc:paginacao>

        </div>
    </div>
</section>

src/web/EnterpriseApp.WebApp.MVC/Views/Catalog/ProductDetails.cshtml
@using EnterpriseApp.WebApp.MVC.Extensions
@model EnterpriseApp.WebApp.MVC.Models.ProductViewModel
@{
    ViewData["Title"] = Model.Name;
}
<section class="section-content padding-y bg container">
    <div class="card">
        <div class="row no-gutters">
            <aside class="col-md-6">
                <article class="gallery-wrap">
                    <div class="img-big-wrap" style="text-align: center">
                        <img src="~/images/produtos/@Model.Image" alt="@Model.Name">
                    </div>
                </article>
            </aside>
            <main class="col-md-6 border-left">
                <article class="content-body">
                    <form asp-controller="Cart" asp-action="AddItemAtCart" method="post">

                        <input type="hidden" id="ProductId" name="ProductId" value="@Model.Id" />

                        <h2 class="title">@Model.Name</h2>

                        <div class="rating-wrap my-3">
                            <ul class="rating-stars">
                                <li style="width: 80%" class="stars-active">
                                    <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                </li>
                                <li>
                                    <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                </li>
                            </ul>
                            <small class="label-rating text-muted">132 avaliações</small>
                            <small class="label-rating text-success"> <i class="fa fa-clipboard-check"></i> 154 peças vendidas</small>
                        </div>

                        <div class="mb-3">
                            <var class="price h4">@this.FormatCurrency(Model.Price)</var>
                        </div>

                        <h5>@Model.Description</h5><br />
                        <p> @this.StockMessage(Model.StockQuantity)</p>

                        <hr>

                        @{
                            if (Model.StockQuantity> 0)
                            {
                                <div class="form-row">
                                    <div class="form-group col-md flex-grow-0">
                                        <label>Quantidade</label>
                                        <div class="input-group input-spinner">
                                            <select id="Quantity" name="Quantity" class="form-control">
                                                <option value="1">1</option>
                                                <option value="2">2</option>
                                                <option value="3">3</option>
                                                <option value="4">4</option>
                                                <option value="5">5</option>
                                            </select>
                                        </div>
                                    </div>

                                </div>
                                <br />
                                <button type="submit" class="btn  btn-outline-primary">
                                    <span class="text">Adicionar ao carrinho</span> <i class="fas fa-shopping-cart"> &nbsp;</i>
                                </button>

                            }
                        }

                        <a asp-action="Index" class="btn  btn-info">
                            <span class="text">Voltar</span>
                        </a>
                    </form>
                </article>
            </main>
        </div>
    </div>
</section>